#!/usr/bin/env python3
"""Development CLI shim — reads prompt from stdin, returns stub-style JSON."""

from __future__ import annotations

import json
import sys


def main() -> int:
    prompt = sys.stdin.read()
    lowered = prompt.lower()
    if "out of memory" in lowered or "oom" in lowered:
        verdict = "operator_actionable"
        summary = "Resource constraint detected in diagnostics."
        confidence = "high"
        actions = ["Reduce model size or disable unused deployments."]
    elif "exit_code" in lowered and "degraded" in lowered:
        verdict = "likely_bug"
        summary = "Unexpected process exit during reconciliation."
        confidence = "medium"
        actions = ["Avoid further config changes until support completes review."]
    else:
        verdict = "insufficient_data"
        summary = "Not enough signal in the submitted bundle."
        confidence = "low"
        actions = ["Add an admin note describing expected vs actual behavior."]

    payload = {
        "verdict": verdict,
        "summary": summary,
        "confidence": confidence,
        "recommended_actions": actions,
        "engineering_notes": "Generated by ai_diagnose_stub.py for local development.",
        "evidence": ["cli_stub"],
    }
    sys.stdout.write(json.dumps(payload))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())